<?php
if(ff)
{
getcourse($userid,'UGTHEORY','ugcourses');
getcourse($userid,'UGLAB','ugcourseslab');
getcourse($userid,'UGELECTIVE','ugopenelective');
getcourse($userid,'PGTHEORY','pgcourses');
getcourse($userid,'PGLAB','pgcourseslab');
getcourse($userid,'PGELECTIVE','pgopenelective');
}
?>